# This is a template for how config files should look, all parameters are in chronological order of use
# All boolean variables are in UPPERCASE lettering
global:
  PREPROCESSING: True
  HYPER_SEARCH: False
  PRE_TRAINING: False
  FINE_TUNING: False

  n_jobs: 14
  random_state: null # remember null and not None

  n_channels: 2
  channel_select_function: 'adjacent_groups'  # How to select pairs of channels to keep
  s_freq: 200
  window_size: 30  # Window length in seconds
  embedding_size: 40
  magic_constant: 49 #TODO find a way to fix this


  # datasets: ['tuh_eeg', 'tuh_eeg_abnormal_eval', 'tuh_eeg_abnormal_train', 'seed', 'bciciv_1'] # which datasets should be preprocessed
  datasets: [ 'tuh_eeg_abnormal_finetune' ] # which datasets should be preprocessed


preprocess:
  tuh_eeg:
    ds_name: 'tuh_eeg'  # Must match key
    dataset_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/tuh_eeg'
    preprocess_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/tuh_eeg_pre'
    IS_FINE_TUNING_DS: False
    STOP_AFTER_PREPROC: False

    start_idx: 0
    stop_idx: null # Which idx is the last to load? (null for all)
    read_cache: 'none'  # Read pickled dataset or generate new. Allowed ['none', 'raw', 'windows', 'preproc', 'split']

    bandpass_lo: 0.3
    bandpass_hi: 80
    scaling_factor: 1000000  # Scaling factor to convert to microVolts
    reject_high_threshold: 8000  # Reject windows with higher peak-to-peak than this (V)
    reject_flat_threshold: 1  # Reject windows flatter than this peak-to-peak (V)
    DELETE_STEP_1: False
    exclude_channels: [ ]  # remember to comment out if not used

  tuh_eeg_abnormal_train: # This key must match one value in params_all['global']['datasets']
    ds_name: 'tuh_eeg_abnormal_train'  # Must match key
    dataset_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/tuh_eeg_abnormal/v3.0.0/edf/train'
    preprocess_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/abnormal_train_pre'
    IS_FINE_TUNING_DS: False
    STOP_AFTER_PREPROC: False

    start_idx: 0
    stop_idx: null  # Which idx is the last to load? (null for all)
    read_cache: 'none'  # Read pickled dataset or generate new. Allowed ['none', 'raw', 'windows', 'preproc', 'split']

    bandpass_lo: 0.3
    bandpass_hi: 80
    scaling_factor: 1000000  # Scaling factor to convert to microVolts
    reject_high_threshold: 8000  # Reject windows with higher peak-to-peak than this (V)
    reject_flat_threshold: 1  # Reject windows flatter than this peak-to-peak (V)
    DELETE_STEP_1: False
    exclude_channels: [ ]  # remember to comment out if not used

  seed:
    ds_name: 'seed'  # Must match key
    dataset_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/SEED/seed_raw'
    preprocess_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/SEED/seed_pre'
    IS_FINE_TUNING_DS: False
    STOP_AFTER_PREPROC: False

    start_idx: 0
    stop_idx: null  # Which idx is the last to load? (null for all)
    read_cache: 'none'  # Read pickled dataset or generate new. Allowed ['none', 'raw', 'windows', 'preproc', 'split']

    channel_select_function: 'adjacent_groups'  # How to select pairs of channels to keep
    bandpass_lo: 0.3
    bandpass_hi: 80
    scaling_factor: 1000000  # Scaling factor to convert to microVolts
    reject_high_threshold: null  # Reject windows with higher peak-to-peak than this (V)
    reject_flat_threshold: null  # Reject windows flatter than this peak-to-peak (V)
    DELETE_STEP_1: False
    exclude_channels: [ ]  # remember to comment out if not used

  bciciv_1:
    ds_name: 'bciciv_1'  # Must match key
    dataset_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/bciciv_1/bciciv_1_raw'
    preprocess_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/bciciv_1/preprocessed'
    IS_FINE_TUNING_DS: False
    STOP_AFTER_PREPROC: False

    start_idx: 0
    stop_idx: null  # Which idx is the last to load? (null for all)
    read_cache: 'none'  # Read pickled dataset or generate new. Allowed ['none', 'raw', 'windows', 'preproc', 'split']

    channel_select_function: 'adjacent_groups'  # How to select pairs of channels to keep
    bandpass_lo: 0.3
    bandpass_hi: 80
    scaling_factor: 0.1  # Scaling factor to convert to microVolts
    reject_high_threshold: 8000  # Reject windows with higher peak-to-peak than this (uV)
    reject_flat_threshold: 1  # Reject windows flatter than this peak-to-peak (uV)
    DELETE_STEP_1: False
    exclude_channels: [ ]  # remember to comment out if not used

  # Abnormal eval is only used for testing after fine_tune
  tuh_eeg_abnormal_eval: # This key must match one value in params_all['global']['datasets']
    ds_name: 'tuh_eeg_abnormal_eval'  # Must match key
    dataset_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/tuh_eeg_abnormal/v3.0.0/edf/eval'
    preprocess_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/abnormal_eval_pre'
    IS_FINE_TUNING_DS: True
    STOP_AFTER_PREPROC: True

    start_idx: 0
    stop_idx: null  # Which idx is the last to load? (null for all)
    read_cache: 'none'  # Read pickled dataset or generate new. Allowed ['none', 'raw', 'windows', 'preproc', 'split']

    bandpass_lo: 0.3
    bandpass_hi: 80
    scaling_factor: 1000000  # Scaling factor to convert to microVolts
    reject_high_threshold: 8000  # Reject windows with higher peak-to-peak than this (V)
    reject_flat_threshold: 1  # Reject windows flatter than this peak-to-peak (V)
    DELETE_STEP_1: False
    exclude_channels: [ ]
    include_channels:  # Include only these channels
      [ 'EEG FP1-REF', 'EEG FP2-REF', 'EEG F3-REF', 'EEG F4-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG P3-REF', 'EEG P4-REF', 'EEG O1-REF', 'EEG O2-REF', 'EEG F7-REF', 'EEG F8-REF', 'EEG T3-REF', 'EEG T4-REF', 'EEG T5-REF', 'EEG T6-REF', 'EEG A1-REF', 'EEG A2-REF', 'EEG FZ-REF', 'EEG CZ-REF', 'EEG PZ-REF', 'EEG T1-REF', 'EEG T2-REF' ]


  tuh_eeg_abnormal_finetune: # Must match ds_name
    ds_name: 'tuh_eeg_abnormal_finetune'  # Must match key
    dataset_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/tuh_eeg_abnormal/v3.0.0/edf/train'
    preprocess_root: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/abnormal_train_pre_finetune'
    IS_FINE_TUNING_DS: True
    STOP_AFTER_PREPROC: True
    target_name: 'pathological'

    start_idx: 0
    stop_idx: null  # Which idx is the last to load? (null for all)
    read_cache: 'preproc'  # needs to be none if new channels are excluded, else windows is acceptable

    bandpass_lo: 0.3
    bandpass_hi: 80
    scaling_factor: 1000000  # Scaling factor to convert to microVolts
    reject_high_threshold: 8000  # Reject windows with higher peak-to-peak than this (V)
    reject_flat_threshold: 1  # Reject windows flatter than this peak-to-peak (V)
    DELETE_STEP_1: False
    exclude_channels: [ ]
    include_channels:
      [ 'EEG FP1-REF', 'EEG FP2-REF', 'EEG F3-REF', 'EEG F4-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG P3-REF', 'EEG P4-REF', 'EEG O1-REF', 'EEG O2-REF', 'EEG F7-REF', 'EEG F8-REF', 'EEG T3-REF', 'EEG T4-REF', 'EEG T5-REF', 'EEG T6-REF', 'EEG A1-REF', 'EEG A2-REF', 'EEG FZ-REF', 'EEG CZ-REF', 'EEG PZ-REF', 'EEG T1-REF', 'EEG T2-REF' ]


pre_training:
  datasets: [ 'tuh_eeg', 'tuh_eeg_abnormal_train' ]

  pretrained_model_path: null # this is the path of an already pretrained model which you wish to continue training (remember null)

  batch_size: 16
  train_split: 0.01
  SHUFFLE: True
  temperature: 1 # Temperature of normalized temperature contrastive loss
  learning_rate: 0.1
  weight_decay: 0.01
  max_epochs: 1

  save_freq: 1
  batch_print_freq: 5
  save_dir_model: 'models' # directory which you wish to store your model to
  model_file_name: 'test' # Name of your model
  TIME_PROCESS: False

  augmentation:
    noise_probability: 0


fine_tuning:
  ds_name: 'tuh_eeg_abnormal'
  # get encoder path from pre_training params
  ds_path: '../datasets/TUH/tuh_eeg_abnormal_preprocessed_finetune/pickles/windowed_ds.pkl'
  encoder_path: 'models/encoder_test'

  n_classes: 2

  batch_size: 16
  max_epochs: 1
  lr_rate: 0.01
  weight_decay: 0.005
  train_split: 0.7
  SHUFFLE: True

  PERFORM_KFOLD: False # should be false when hyperparametersearching,
  n_folds: 5

  early_stopper: #params for early stopper implementation
    patience: 4
    min_delta: 0.1

  save_dir_model: 'models_fine_tune' # directory which you wish to store your model to
  model_file_name: 'test' # Name of your model

  REDO_PREPROCESS: False # this must allways be true, as preprocessing always have to be done before pretraining.
  fine_tuning_preprocess:
    ds_name: 'tuh_eeg_abnormal'
    dataset_root: 'C:/Users/Styrk/OneDrive-NTNU/Documents/Skole/Master/master_code/master-eeg-trans/datasets/TUH/tuh_eeg_abnormal/v3.0.0/edf/train'
    preprocess_root: 'C:/Users/Styrk/OneDrive-NTNU/Documents/Skole/Master/master_code/master-eeg-trans/datasets/TUH/tuh_eeg_abnormal_preprocessed_finetune'
    IS_FINE_TUNING_DS: True
    target_name: 'pathological'

    start_idx: 0
    stop_idx: 10  # Which idx is the last to load? (null for all)
    read_cache: 'none'  # needs to be none if new channels are excluded, else windows is acceptable

    bandpass_lo: 0.3
    bandpass_hi: 80
    scaling_factor: 1000000  # Scaling factor to convert to microVolts
    reject_high_threshold: 800  # Reject windows with higher peak-to-peak than this (V)
    reject_flat_threshold: 0.00000  # Reject windows flatter than this peak-to-peak (V)
    DELETE_STEP_1: True
    exclude_channels:
      - 'EEG 26-REF'
      - 'EEG 27-REF'
      - 'EEG 28-REF'
      - 'EEG 29-REF'
      - 'EEG 30-REF'

encoder_params:
  temporal_size: 40
  spatial_size: 40
  CNN_dropout: 0.5

  n_encoder_heads: 10
  n_encoder_layers: 6

  latent_space_size: 64

downstream_params:
  out_layer_1: 256
  out_layer_2: 64
  dropout_1: 0.5
  dropout_2: 0.3

hyper_search:
  PERFORM_PREPROCESS: False
  PREPROCESS: True # wether you need correct paths when there is changes to preprocess but they are already loeaded
  FINE_AND_PRE: True # Need to know which one has parameter changes, both can't have
  PRE_TRAINING: False # only used when you only do pre_training
  FINE_TUNING: False
  max_t: 10

  config:
    n_channels: 'tune.grid_search([2,3,4,5])'
    #batch_size: 'tune.choice([16,32,128])'
    #lr_rate: 'tune.loguniform(1e-4, 1e-1)'


  inspiration:
    l1: 'tune.sample_from(lambda _: 2 ** np.random.randint(2, 9))'
    l2: 'tune.sample_from(lambda _: 2 ** np.random.randint(2, 9))'
    lr: 'tune.loguniform(1e-4, 1e-1)'
    batch_size: 'tune.choice([2, 4, 8, 16])'

# TODO: avoid preprocessing every time.